# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Manoj Action in compled!"}' $SLACK_WEBHOOK_URL
